<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/9/10 0010
 * Time: 21:45
 */
require_once 'Shop.php';
class Phone extends Shop
{
  private $brand;
  private $city;
  // 重写构造方法
  public function __construct($name2, $price2, $brand2, $city2)
  {
    // 调用父亲的构造方法
    parent::__construct($name2, $price2);
    // 初始化自己的成员属性
    $this->brand = $brand2;
    $this->city  = $city2;
  }
  // 重写普通测成员方法
  public function showInfo()
  {
    $str = parent::showInfo(); // TODO: Change the autogenerated stub
    $str .= "<br>手机品牌：{$this->brand}";
    $str .= "<br>销售城市：{$this->city}";
    echo $str;
  }

}