<?php
/**
 * 商品：电脑类
 */
require_once 'Commodity.php';
// 方法重写
class Computer extends Commodity
{
  public $name = '珊珊';
  public static function readMe()
  {
//    return parent::readMe(); // TODO: Change the autogenerated stub
    $str = "我是子类写的方法";
    $str .= parent::readMe();
    echo $str;
  }
}
